### ISSUE TITLE
Error while running migrations.

### ISSUE THREAD

**Issue by harisibrahimkv** [klpdotorg/tada#14]
Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying schools.0001_initial...Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(_args, *_options)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 385, in add_field
    definition, params = self.column_sql(model, field, include_default=True)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 142, in column_sql
    default_value = self.effective_default(field)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 207, in effective_default
    default = field.get_db_prep_save(default, self.connection)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1940, in get_db_prep_save
    return self.related_field.get_db_prep_save(value, connection=connection)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/models/fields/**init**.py", line 710, in get_db_prep_save
    prepared=False)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/models/fields/**init**.py", line 977, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/models/fields/**init**.py", line 985, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'ed'

@vinayakh

**Comment by vinayakh** [comment]
yeah @batpad is also getting this error. We plan to fix this and other errors day after.

**Comment by harisibrahimkv** [comment]
Ah okay. @vinayakh I think this line is the problem: https://github.com/klpdotorg/tada/blob/master/apps/schools/migrations/0001_initial.py#L456

**Comment by harisibrahimkv** [comment]
@vinayakh There are two places where a "string" has been specified as the default for a ForeignKey value. While I don't have enough knowledge to say that this is \* not \* possible, removing the defaults actually made it work.
1. In the Institution model:

```
-    mgmt = models.ForeignKey(Institution_Management, default='ed')
+    mgmt = models.ForeignKey(Institution_Management)
```

and in the migration:

```
-            field=models.ForeignKey(default=b'ed', to='schools.Institution_Management'),
+            field=models.ForeignKey(to='schools.Institution_Management'),
```
1. In the Child model:

```
-    mt = models.ForeignKey(Moi_Type, default='kannada')
+    mt = models.ForeignKey(Moi_Type)
```

and in the migration:

```
-            field=models.ForeignKey(default=b'kannada', to='schools.Moi_Type'),
+            field=models.ForeignKey(to='schools.Moi_Type'),
```

@batpad Making these changes helped me run the migrations smooth.

**Comment by iambibhas** [comment]
The ForeignKey is to `Institution_Management` which has a `AutoField` primary key. Hence Django turns the ForeignKey field into an Integer Field in the DB. That's why `ed` was giving the trouble.

**Comment by iambibhas** [comment]
We should check the `Institution_Management` in db and see if it's primary key is integer, if not then change the autofield maybe.

**Comment by vinayakh** [comment]
@iambibhas yes the primary key is an intgere in the table. Will change and commit changes.

**Comment by vinayakh** [comment]
Fixed in commit - https://github.com/klpdotorg/tada/commit/c2e776057dd340904f5206602397ab0ceb9013de

**Comment by harisibrahimkv** [comment]
@vinayakh I think you need to change the "mt" field in the Child model as well.

**Comment by vinayakh** [comment]
Fixed medium of instruction in https://github.com/klpdotorg/tada/commit/1fa14cbd2aeb339b328cf5edac10c6fc2494b63c
