### ISSUE TITLE
Migration error.

### ISSUE THREAD

**Issue by harisibrahimkv** [klpdotorg/tada#28]
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying schools.0001_initial... OK
  Applying schools.0002_auto_20150519_2205... OK
  Applying schools.0003_auto_20150521_1211... OK
  Applying schools.0004_auto_20150525_1357...Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(_args, *_options)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 217, in database_forwards
    to_field,
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 469, in alter_field
    return self._alter_many_to_many(model, old_field, new_field, strict)
  File "/home/haris/Envs/tada/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 780, in _alter_many_to_many
    new_field.rel.through._meta.get_field(new_field.m2m_reverse_field_name()),
AttributeError: 'ManyToManyField' object has no attribute 'm2m_reverse_field_name'
(tada)haris@insanity:~/klp/tada$

**Comment by subhaklp** [comment]
Yes, same error here.

**Comment by harisibrahimkv** [comment]
@vinayakh @subhaklp The solution is to upgrade your Django. `pip install -r requirements/base.txt` should fix it. Closing this.
